---

default_language_version:
    python: python3.9
minimum_pre_commit_version: 2.17.0

repos:

  - repo: https://github.com/jazzband/pip-tools
    rev: 6.5.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args:
          - '--allow-unsafe'
          - '--annotate'
          - '--annotation-style=split'
          - '--build-isolation'
          - '--verbose'
          - '--pip-args="--verbose"'
          - requirements.in
        verbose: true
        files: ^requirements\.(in|txt)$
